<?php

use App\Enums\CounsellorPayoutStatusEnum;
use App\Models\Counsellor;
use App\Models\User;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        // TT-7.6c/SCRUM-227: a payout batch (may span several CounsellorEarning rows).
        // `reference` mirrors `transactions.reference`'s role exactly -- generated by us, sent to
        // Paystack as the Transfer's own `reference`, and the correlation key a later webhook
        // uses to find this row again.
        Schema::create('counsellor_payouts', function (Blueprint $table) {
            $table->id();
            $table->foreignIdFor(Counsellor::class)->constrained();
            // Always set -- the counsellor's own user_id for self-service, or the admin's for an
            // admin-triggered payout. Never null: every payout has an accountable initiator.
            $table->foreignIdFor(User::class, 'initiated_by_id')->constrained('users');
            $table->string('reference')->unique();
            // Paystack's own Transfer identifier, set once the initiate call succeeds -- null
            // until then, and null forever if the initiate call itself fails outright.
            $table->string('transfer_code')->nullable();
            // Minor units (pesewas/cents), same convention as transactions.amount.
            $table->unsignedBigInteger('amount');
            $table->string('currency', 3);
            $table->enum('status', CounsellorPayoutStatusEnum::values())->default(CounsellorPayoutStatusEnum::pending->value);
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('counsellor_payouts');
    }
};
